#!/bin/sh

ENABLED=yes
PROCS=bird
ARGS="-c /opt/etc/$PROCS.conf -P /opt/var/run/$PROCS.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
