#!/bin/sh

ENABLED=yes
PROCS=bird
ARGS="-f -c /opt/etc/bird.conf -P /opt/var/run/bird.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
